PreHookHandlers = {}

function PreHookHandlers:Initialize()
  ZO_PreHookHandler(
    ZO_GameMenu_InGame,
    "OnShow",
    function()
      CrownPointerThing.reticle.SetHidden(true)
      ProvinatusCompass:SetHidden(true)
      ProvinatusHUD:SetHidden(true)
    end
  )
  ZO_PreHookHandler(
    ZO_GameMenu_InGame,
    "OnHide",
    function()
      CrownPointerThing.reticle.SetHidden(false)
      ProvinatusCompass:SetHidden(false)
      ProvinatusHUD:SetHidden(false)
    end
  )
  ZO_PreHookHandler(
    ZO_InteractWindow,
    "OnShow",
    function()
      CrownPointerThing.reticle.SetHidden(true)
      ProvinatusCompass:SetHidden(true)
      ProvinatusHUD:SetHidden(true)
    end
  )
  ZO_PreHookHandler(
    ZO_InteractWindow,
    "OnHide",
    function()
      CrownPointerThing.reticle.SetHidden(false)
      ProvinatusCompass:SetHidden(false)
      ProvinatusHUD:SetHidden(false)
    end
  )
  ZO_PreHookHandler(
    ZO_KeybindStripControl,
    "OnShow",
    function()
      CrownPointerThing.reticle.SetHidden(true)
      ProvinatusCompass:SetHidden(true)
      ProvinatusHUD:SetHidden(true)
    end
  )
  ZO_PreHookHandler(
    ZO_KeybindStripControl,
    "OnHide",
    function()
      CrownPointerThing.reticle.SetHidden(false)
      ProvinatusCompass:SetHidden(false)
      ProvinatusHUD:SetHidden(false)
    end
  )
  ZO_PreHookHandler(
    ZO_MainMenuCategoryBar,
    "OnShow",
    function()
      CrownPointerThing.reticle.SetHidden(true)
      ProvinatusCompass:SetHidden(true)
      ProvinatusHUD:SetHidden(true)
    end
  )
  ZO_PreHookHandler(
    ZO_MainMenuCategoryBar,
    "OnHide",
    function()
      CrownPointerThing.reticle.SetHidden(false)
      ProvinatusCompass:SetHidden(false)
      ProvinatusHUD:SetHidden(false)
    end
  )
end
